import { TourStep } from "@/lib/types/tour";

export const TOUR_STEPS: TourStep[] = [
  {
    id: "welcome-hero",
    route: "/",
    targetElementSelector: "[data-tour='hero-cta']",
    placement: "bottom",
    title: "1. WELCOME TO FINORA",
    subtitle: "Deterministic Education Loan Pre-Underwriting",
    tag: "START HERE",
    accentColor: "yellow",
    description:
      "Finora eliminates study-abroad loan rejection surprises. Instead of opaque lead-gen forms, we run verified mathematical underwriting models against official bank guidelines before you apply.",
    keyTakeaways: [
      "100% deterministic evaluation — zero black-box AI approximations",
      "Instant evaluation of tuition, living expenses, and FX conversions",
      "Direct guidance for public banks, private financiers, and specialist NBFCs",
    ],
    actionTip: "Let's explore our core architectural pillars below →",
  },
  {
    id: "landing-pillars",
    route: "/",
    targetElementSelector: "[data-tour='pillars-section']",
    placement: "top",
    title: "2. THE 3 UNDERWRITING PILLARS",
    subtitle: "Connected Context, Bounded Actions & Verified Results",
    tag: "CORE ARCHITECTURE",
    accentColor: "pink",
    description:
      "Finora is built upon three non-negotiable principles: keeping candidate context unified, enforcing bank-mandated borrowing boundaries, and verifying results with full audit transparency.",
    keyTakeaways: [
      "Connected Context: Degree, budget, co-borrower income, and collateral stay unified",
      "Bounded Actions: Out-of-scope loans are automatically flagged with playbooks",
      "Verified Results: Transparent mathematical models replace opaque approval guesses",
    ],
    actionTip: "Next, let's inspect a live case receipt with complete audit trails →",
  },
  {
    id: "landing-receipt",
    route: "/",
    targetElementSelector: "[data-tour='receipt-box']",
    placement: "top",
    title: "3. TRANSPARENT AUDIT RECEIPT",
    subtitle: "Every Loan Rule Has a Verifiable Trail",
    tag: "ZERO DRIFT",
    accentColor: "cyan",
    description:
      "Inspect this verified case receipt. Finora computes currency conversions, co-borrower FOIR obligations, and collateral haircuts in clear view so students and counselors can inspect the exact math.",
    keyTakeaways: [
      "Itemized study budgets normalized to Indian Rupees (INR)",
      "Co-borrower income vs debt obligations mapped to bank safety bands",
      "Exact haircut discounts calculated for pledged property & liquid assets",
    ],
    actionTip: "Let's see how our underwriting pipeline operates step-by-step →",
  },
  {
    id: "landing-how-it-works",
    route: "/",
    targetElementSelector: "[data-tour='how-it-works-section']",
    placement: "top",
    title: "4. FROM REPORT TO READ BACK",
    subtitle: "Structured 3-Stage Pre-Underwriting Pipeline",
    tag: "WORKFLOW",
    accentColor: "mint",
    description:
      "See how candidate data moves through our engine: 1) Read target university fee structures, 2) Bound borrowing limits via FOIR & collateral, and 3) Read back verified lender verdicts.",
    keyTakeaways: [
      "Stage 1: Validates study expenses against official I-20 thresholds",
      "Stage 2: Restricts debt requests to bank-sanctionable parameters",
      "Stage 3: Generates exportable, tamper-proof counselor dossiers",
    ],
    actionTip: "Now let's check the top navigation bar to explore the tools suite →",
  },
  {
    id: "nav-suite",
    route: "/",
    targetElementSelector: "[data-tour='nav-menu']",
    placement: "bottom",
    title: "5. THE COMPLETE TOOLS SUITE",
    subtitle: "Direct Access to Simulators, Matrices & Evidence Vaults",
    tag: "NAVIGATION",
    accentColor: "yellow",
    description:
      "From this header navigation bar, students and loan advisors can jump directly into the debt simulator, inspect official lender policies, or audit documents in the OCR vault.",
    keyTakeaways: [
      "FOIR Simulator: Real-time debt affordability stress-tester",
      "Lender Rules: Comprehensive underwriting matrix and CIBIL cutoffs",
      "Documents & OCR: Dynamic evidence checklist with discrepancy detection",
    ],
    actionTip: "Let's travel to the live 6-step loan assessment wizard →",
  },
  {
    id: "assessment-wizard",
    route: "/assessment",
    targetElementSelector: "[data-tour='assessment-wizard']",
    placement: "top",
    title: "6. 6-STAGE ELIGIBILITY WIZARD",
    subtitle: "Comprehensive Intake from Profile to Collateral Haircuts",
    tag: "EVALUATION ENGINE",
    accentColor: "pink",
    description:
      "Our 6-step wizard captures complete borrower context: 1) Student KYC, 2) Target country and university, 3) Self-funding gap, 4) Co-borrower salary/ITR, 5) Pledged collateral, and 6) Multi-lender matching.",
    keyTakeaways: [
      "Step-by-step progress tracking with instant field validation",
      "Automatic 0.5% interest rate discount applied for female students",
      "Calculates total net worth, unencumbered assets, and funding shortfall",
    ],
    actionTip: "Let's examine the multi-currency conversion engine on this form →",
  },
  {
    id: "assessment-fx-engine",
    route: "/assessment",
    targetElementSelector: "[data-tour='assessment-form-container']",
    placement: "top",
    title: "7. MULTI-CURRENCY FX ENGINE",
    subtitle: "Unified Conversion for Global University Costs",
    tag: "FX ENGINE",
    accentColor: "cyan",
    description:
      "Enter tuition and living costs in foreign currencies (USD, GBP, EUR, CAD, AUD). Finora automatically converts all figures to Indian Rupees (INR) using verified central bank exchange benchmarks.",
    keyTakeaways: [
      "Supports Tier-1 study currencies: USD, GBP, EUR, CAD, AUD",
      "Itemizes living expenses, visa fees, and health insurance",
      "Eliminates FX conversion errors and currency fluctuation surprises",
    ],
    actionTip: "Next, let's explore Original Feature #1: The live FOIR simulator →",
  },
  {
    id: "simulator-tool",
    route: "/simulator",
    targetElementSelector: "[data-tour='foir-simulator-card']",
    placement: "bottom",
    title: "8. REAL-TIME FOIR SIMULATOR",
    subtitle: "Original Feature #1: Stress-Test Debt Capacity Live",
    tag: "FEATURE 1",
    accentColor: "mint",
    description:
      "Exceeding bank FOIR limits (>50%) causes over 80% of education loan rejections. This interactive tool lets you slide loan amounts, tenures (up to 15 years), and income in real-time to preview dynamic risk bands.",
    keyTakeaways: [
      "Live amortizing monthly EMI recalculation with zero server lag",
      "Instant FOIR calculation: (Existing EMIs + New EMI) / Monthly Income",
      "Interactive sliders for loan amount, tenure, and interest rate",
    ],
    actionTip: "Let's inspect the lender risk threshold benchmarks below →",
  },
  {
    id: "simulator-benchmarks",
    route: "/simulator",
    targetElementSelector: "[data-tour='foir-risk-benchmarks']",
    placement: "top",
    title: "9. LENDER FOIR RISK BENCHMARKS",
    subtitle: "Color-Coded Risk Bands & Actionable Remediation",
    tag: "RISK ENGINE",
    accentColor: "yellow",
    description:
      "Understand how lenders interpret your debt burden. Finora categorizes risk into 4 clear bands and provides actionable playbooks when your ratio exceeds safe PSU limits.",
    keyTakeaways: [
      "Safe Band (≤40%): Prime public and private bank approvals",
      "Moderate Band (40-50%): Standard PSU threshold ceiling",
      "Stretched & High (>50%): Requires co-borrower addition or tenure extension",
    ],
    actionTip: "Let's visit the official Lender Underwriting Matrix next →",
  },
  {
    id: "lenders-matrix",
    route: "/lenders",
    targetElementSelector: "[data-tour='lenders-filter-bar']",
    placement: "bottom",
    title: "10. LENDER CATEGORY DIRECTORY",
    subtitle: "Filter by Public Banks, Private Banks, NBFCs & Fintechs",
    tag: "LENDER MATRIX",
    accentColor: "pink",
    description:
      "Filter the underwriting database by institution type or search for specific lenders. Each category reflects distinct margin money requirements, moratorium terms, and collateral rules.",
    keyTakeaways: [
      "Public Banks: SBI, Bank of Baroda, Bank of India (lowest rates, collateral)",
      "Private Banks: ICICI, Axis, HDFC Bank (flexible limits, fast turnarounds)",
      "NBFCs & Fintechs: HDFC Credila, Auxilo, Prodigy Finance (unsecured options)",
    ],
    actionTip: "Let's inspect the verified policy rules database below →",
  },
  {
    id: "lenders-rules",
    route: "/lenders",
    targetElementSelector: "[data-tour='lenders-grid']",
    placement: "top",
    title: "11. LIVE LENDER POLICY RULES",
    subtitle: "Verified Interest Slabs, CIBIL Benchmarks & Max Limits",
    tag: "POLICY RULES",
    accentColor: "cyan",
    description:
      "Inspect the exact criteria programmed into our engine: minimum CIBIL score cutoffs, maximum loan caps (up to ₹1.5 Cr), indicative interest rate brackets, and tangible collateral mandates.",
    keyTakeaways: [
      "Official CIBIL score minimums (e.g. SBI 750+, Private 680+)",
      "Collateral-free vs tangible collateral requirements clearly flagged",
      "Real-time policy verification badges with traceable rule IDs",
    ],
    actionTip: "Now let's check Original Feature #3: The Pre-Underwriting Document Vault →",
  },
  {
    id: "document-vault",
    route: "/documents",
    targetElementSelector: "[data-tour='document-upload-zone']",
    placement: "bottom",
    title: "12. PRE-UNDERWRITING DOCUMENT VAULT",
    subtitle: "Original Feature #3: Dynamic Checklists & Magic-Byte Verification",
    tag: "FEATURE 3",
    accentColor: "mint",
    description:
      "The vault builds a dynamic evidence checklist tailored to your loan route (collateral vs non-collateral) with isolated file storage and magic-byte MIME validation for maximum file security.",
    keyTakeaways: [
      "Contextual checklists: Title deeds for secured loans; ITR-Vs for unsecured loans",
      "Magic-byte validation: Verifies authentic PDF, PNG, and JPEG binaries",
      "Instant readiness tracker: Total required, uploaded, and missing items",
    ],
    actionTip: "Let's inspect our automated OCR discrepancy detection engine →",
  },
  {
    id: "document-ocr",
    route: "/documents",
    targetElementSelector: "[data-tour='ocr-discrepancy-section']",
    placement: "top",
    title: "13. AUTOMATED OCR DISCREPANCY AUDIT",
    subtitle: "Detect Income & KYC Mismatches Before Lenders Do",
    tag: "OCR AUDIT",
    accentColor: "yellow",
    description:
      "Lenders reject applications when declared income differs from uploaded proof. Our automated OCR engine cross-checks declared numbers against ITR-Vs and salary slips to flag variances in advance.",
    keyTakeaways: [
      "Automated OCR extraction from Form 16, ITR-V, and salary slips",
      "Highlights variance amounts (e.g. Declared ₹1.85L vs Extracted ₹1.82L)",
      "Severity indicators (Warning vs Critical) with corrective advice",
    ],
    actionTip: "Let's complete the tour and return to the home screen →",
  },
  {
    id: "finish-tour",
    route: "/",
    targetElementSelector: "[data-tour='hero-cta']",
    placement: "bottom",
    title: "14. YOU'RE READY TO UNDERWRITE!",
    subtitle: "Full Platform Walkthrough Completed 🎉",
    tag: "COMPLETED",
    accentColor: "mint",
    description:
      "You have explored every core capability of the Finora platform. You are now equipped to run deterministic loan evaluations, stress-test debt scenarios, and verify documents with zero surprises.",
    keyTakeaways: [
      "Evaluate Candidate: Start a fresh 6-stage assessment with lender matching",
      "Advisor Dossiers: Generate tamper-proof, printable audit reports",
      "Replay Tour: Click 'HOW IT WORKS' in the navbar anytime to review",
    ],
    actionTip: "Click 'Finish Tour' to explore freely on your own!",
  },
];
