import { TourStep } from "@/lib/types/tour";

export const TOUR_STEPS: TourStep[] = [
  {
    id: "welcome-hero",
    route: "/",
    targetElementSelector: "[data-tour='hero-cta']",
    placement: "bottom",
    title: "1. WELCOME TO FINORA",
    subtitle: "Deterministic Education Loan Pre-Underwriting",
    tag: "START HERE",
    accentColor: "yellow",
    description:
      "Finora eliminates study-abroad loan rejection surprises. Instead of opaque lead-gen forms, we run verified mathematical underwriting models against official bank guidelines before you apply.",
    keyTakeaways: [
      "100% deterministic evaluation — no black-box AI approximations",
      "Instant evaluation of tuition, living expenses, and global currency conversions",
      "Direct guidance for public banks, private financiers, and specialist NBFCs",
    ],
    actionTip: "Let's inspect how calculations are verified on this page →",
  },
  {
    id: "landing-receipt",
    route: "/",
    targetElementSelector: "[data-tour='receipt-box']",
    placement: "top",
    title: "2. TRANSPARENT AUDIT RECEIPT",
    subtitle: "Every Loan Rule Has a Verifiable Trail",
    tag: "ZERO DRIFT",
    accentColor: "cyan",
    description:
      "Notice this verified case receipt. Finora computes currency conversion, co-borrower FOIR obligations, and collateral haircuts in clear view so students and counselors can see the math behind every recommendation.",
    keyTakeaways: [
      "Itemized study budgets normalized to Indian Rupees (INR)",
      "Co-borrower income vs debt obligations mapped to bank safety bands",
      "Exact haircut discounts calculated for pledged property & liquid assets",
    ],
    actionTip: "Now let's check the top navigation bar to explore the tools suite →",
  },
  {
    id: "nav-suite",
    route: "/",
    targetElementSelector: "[data-tour='nav-menu']",
    placement: "bottom",
    title: "3. THE COMPLETE TOOLS SUITE",
    subtitle: "Seamless Access to Simulators, Matrices & Vaults",
    tag: "NAVIGATION",
    accentColor: "mint",
    description:
      "From this header, you can jump directly into the FOIR Debt Simulator, inspect live Lender Underwriting Rules, or audit candidate documents in the OCR Vault.",
    keyTakeaways: [
      "FOIR Simulator: Stress-test monthly EMIs against household income",
      "Lender Rules: Official policy database with boys/girls concessions and CIBIL cutoffs",
      "Documents & OCR: Dynamic evidence checklist with discrepancy detection",
    ],
    actionTip: "Let's travel to the live 6-step loan assessment wizard →",
  },
  {
    id: "assessment-wizard",
    route: "/assessment",
    targetElementSelector: "[data-tour='assessment-wizard']",
    placement: "top",
    title: "4. 6-STAGE ELIGIBILITY WIZARD",
    subtitle: "Comprehensive Intake from Profile to Collateral Haircuts",
    tag: "EVALUATION ENGINE",
    accentColor: "pink",
    description:
      "Here candidates fill out a structured 6-step intake: 1) Student KYC, 2) Target country and university tier, 3) Self-funding gap, 4) Co-borrower salary/ITR, 5) Pledged collateral & haircuts, and 6) Real-time multi-lender matching.",
    keyTakeaways: [
      "Multi-currency conversion engine supporting USD, GBP, EUR, CAD, AUD",
      "Automatic application of 0.5% girl student interest concessions",
      "Instant computation of total net worth, FOIR debt burden, and collateral LTV",
    ],
    actionTip: "Next, let's explore Original Feature #1: The live FOIR simulator →",
  },
  {
    id: "simulator-tool",
    route: "/simulator",
    targetElementSelector: "[data-tour='foir-simulator-card']",
    placement: "bottom",
    title: "5. REAL-TIME FOIR SIMULATOR",
    subtitle: "Original Feature #1: Stress-Test Debt Capacity Live",
    tag: "FEATURE 1",
    accentColor: "mint",
    description:
      "Exceeding bank FOIR limits (>50%) causes over 80% of education loan rejections. This interactive tool lets you slide loan amounts, tenures (up to 15 years), and income in real-time to preview dynamic risk bands and remediation playbooks.",
    keyTakeaways: [
      "Color-coded risk indicators: Safe (≤40%), Moderate (40-50%), Stretched (50-60%), High (>60%)",
      "Live amortizing monthly EMI recalculation with zero server lag",
      "Actionable fixes: Co-borrower additions, tenure elongation, or personal debt payoff",
    ],
    actionTip: "Let's visit the official Lender Underwriting Matrix next →",
  },
  {
    id: "lenders-matrix",
    route: "/lenders",
    targetElementSelector: "[data-tour='lenders-directory']",
    placement: "top",
    title: "6. LIVE LENDER MATRIX",
    subtitle: "Verified Policy Rules for Public Banks, Private Banks & NBFCs",
    tag: "LENDER MATRIX",
    accentColor: "yellow",
    description:
      "Inspect the exact criteria programmed into our engine: SBI (8.40% secured / 9.40% Top 100 univs, CIBIL 750), Bank of Baroda (8.95% boys / 8.75% girls), Bank of India (collateral mandatory), and NBFCs like HDFC Credila & Auxilo.",
    keyTakeaways: [
      "Filter by Public Banks, Private Banks, NBFCs, or USD Fintech options",
      "Official minimum CIBIL score cutoffs and maximum loan amounts",
      "Clear indicators for tangible collateral requirements and university ranking tiers",
    ],
    actionTip: "Now let's check Original Feature #3: The Pre-Underwriting Document Vault →",
  },
  {
    id: "document-vault",
    route: "/documents",
    targetElementSelector: "[data-tour='document-vault-section']",
    placement: "top",
    title: "7. PRE-UNDERWRITING DOCUMENT VAULT",
    subtitle: "Original Feature #3: Dynamic Checklists & OCR Discrepancy Audits",
    tag: "FEATURE 3",
    accentColor: "pink",
    description:
      "Lenders reject files when declared figures differ from uploaded proof. The vault builds a dynamic checklist tailored to your loan route (collateral vs non-collateral) and runs automated OCR extraction to highlight income and KYC discrepancies.",
    keyTakeaways: [
      "Contextual checklists: Title deeds for property loans; ITR-Vs for unsecured loans",
      "Isolated secure storage with file checksums and magic-byte MIME validation",
      "Automated discrepancy flags (e.g. Declared ₹1.85L vs ITR ₹1.82L)",
    ],
    actionTip: "Let's complete the tour and return to the home screen →",
  },
  {
    id: "finish-tour",
    route: "/",
    targetElementSelector: "[data-tour='hero-cta']",
    placement: "bottom",
    title: "8. YOU'RE READY TO UNDERWRITE!",
    subtitle: "Full Platform Walkthrough Completed 🎉",
    tag: "COMPLETED",
    accentColor: "mint",
    description:
      "You have experienced the complete Finora ecosystem across all live pages. You can now evaluate a candidate's loan readiness, test scenarios on the simulator, or restart this guided tour anytime from the top navigation bar.",
    keyTakeaways: [
      "Start Fresh Assessment: 6-step form with multi-lender matching",
      "Counselor Dossiers: Export printable, tamper-proof PDF audit reports",
      "Replay Tour: Click 'HOW IT WORKS' in the navbar whenever you wish",
    ],
    actionTip: "Click 'Finish Tour' to explore freely on your own!",
  },
];
